### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lanechr** [deco3500/apple#1]
I like the way that this idea aims to remove bias through the removal of algorithms, rather than just a different one.
The difficulty here is giving the user the illusion of no boundaries (obviously some algorithm must be created to ensure the comments section isn't just a complete mess). If you can find a way to mask this and provide users an easy to use/understand forum you will go far with this idea.

**Comment by eduardlio** [comment]
Thanks lanechr, the topic of algorithms has come up a few times in bias-moderating discussion; it's definitely something we're considering. Until then, however, we're probably sticking with a human moderator with a search for anomaly posts (e.g. a post being voted both extreme left and right wing, heaps of votes but no comments (low controversy, high votes)).
Thanks again for the feedback :+1:
